import React from "react";
import Head from "next/head";

import Footer from "../common/Footer";
import Header from "../common/Header";

export default function Layout({ headerColor, children }) {
  const [sticky, setSticky] = React.useState(false);

  React.useEffect(() => {
    window.addEventListener("scroll", (e) => {
      setSticky(window.scrollY > 185);
    });

    () =>
      window.removeEventListener("scroll", (e) => {
        setSticky(window.scrollY > 185);
      });
  }, []);

  return (
    <div>
      <Head>
        <title>Slack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/slack.png" />
      </Head>
      <Header headerColor={headerColor} sticky={sticky} />
      <main>{children}</main>
      <Footer setSticky={setSticky} />
    </div>
  );
}
